### ISSUE TITLE
Can't post comment

### ISSUE THREAD

**Issue by Lux-Delux** [jacobwb/hashover-next#76]
Well this is weird

Notice: Undefined index: password in hashover/scripts/writecomments.php on line 96 

On trying to post a comment. Works fine on my test page but get's broken on any one of my websites pages. Same with or without var password_on = false

**Comment by Lux-Delux** [comment]
Also noticed the same message in logs for 
writecomments.php on line 461

**Comment by jacobwb** [comment]
This should be fixed now.

**Comment by Lux-Delux** [comment]
Hmm still having problems...
Since the error is vague now, with only this displayed in browser (linux logs are clear)

document.getElementById('hashover').innerHTML = "HashOver: Failed to create comment thread directory at \"./

maybe it's to do with directory permissions. What was supposed to be for pages/ 

sudo chmod -R 0755 pages/ ?

**Comment by Lux-Delux** [comment]
Oh here we go, log finally picked something?

FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'Cookies' not found in /htdocs/hashover/hashover.php on line 120" while reading response header from upstream

**Comment by jacobwb** [comment]
Make sure that `hashover/pages/` is owned by the user your webserver/PHP is running as, typically "www-data". However, it also looks like you're missing your `hashover/scripts/cookies.php` file, or its permissions are not set to allow your webserver/PHP to read it.

**Comment by Lux-Delux** [comment]
You gave me a good hint, problem was in the ownership of pages. I only had www-data as the group, not owner. Seems to work fine now
